### ISSUE TITLE
trademarking 'ipmjs' so we don't get kik'd

### ISSUE THREAD

**Issue by josheverett** [ipmjs/ipmjs#1]
We’re reaching out to you as we’d very much like to use our name “ipmjs” for an important package that we are going to release soon. Unfortunately, your use of ipmjs (and ipm-cli) mean that we can’t and our users will be confused and/or unable to find our service.

Can we get you to rename your ipmjs service?

We don’t mean to be a dick about it, but it’s a registered Trademark in most countries around the world and if you actually release an open source project called ipmjs, our trademark lawyers are going to be banging on your door and taking down your accounts and stuff like that — and we’d have no choice but to do all that because you have to enforce trademarks or you lose them.

Can we not come to some sort of a compromise to get you to change the name without involving lawyers? Is there something we could do for you in compensation to get you to change the name?

Josh Everett
Instant Pizza Magic Justice Society

**Comment by reimertz** [comment]
@josheverett This is an legit issue that we would have to take care about. <3

**Comment by EdenCoder** [comment]
Anyone called `Instant Pizza Magic Justice Society` can have all of my trademarks; That is the coolest stupid name I have ever seen.

**Comment by camsaul** [comment]
Trademarks are a BASIC need for all magic pizza societies.
