### ISSUE TITLE
Use CD-RW as a medium to store our dependencies?

### ISSUE THREAD

**Issue by reimertz** [ipmjs/ipmjs#14]
I have an idea,

what if a  `ipm install jquery bootstrap --save` result in in an automatic email being sent to me containing:

```
{
  hash: '3gkj6sdq0t89uw9876v5', // unique hash based on installed dependencies and their versions
  packages: [
    'jquery@2.11': '(function()() ....)', //the actual package data
    'bootstrap@3.5': : '(function()() ....)' //the actual package data
 ]
}
```

I then have a system setup that will burn the following data to a CD that I store at home.

When a user later do a `ipm install` again, it will email me again asking for the cd with the following hash: `3gkj6sdq0t89uw9876v5`. The script will be running till I manually read the email, find the CD matching the hash and I reply the email with the content of the CD.

What do you guys think?

**Comment by josh-egan-ps** [comment]
:stuck_out_tongue: :april-fools:

**Comment by lbennett-stacki** [comment]
I think using CD-R over CD-RW will help secure immutability on a hardware level, something no other package manager is offering right now. Also, they're about half the price of CD-RWs. ;)

**Comment by reimertz** [comment]
April fools.
