### ISSUE TITLE
Insensitive Date under 'Motivation'

### ISSUE THREAD

**Issue by jezen** [ipmjs/ipmjs#3]
Great initiative, and I'm not one to join with the Internet's sensitivity police, but I take issue with one thing.

In the project's README:

> Motivation
> 
> March 22, 2016 will forever be remembered for all of us who is hooked on npm and its beautiful  ecosystem of modules.

I find this insensitive to the tragic events that _most of the world_ will remember March 22nd, 2016 for.

**Comment by reimertz** [comment]
Ey man, thanks for catching this.  I was actually flying from Austin and landed in Frankfurt just when this happened. It was some scary shit and I can't imagine how it was for the people Brussels.

Jet lag got me to think 22/3 was the day before I landed.

Again, thanks for pointing this out. I'll remove this klumpsy reference.

**Comment by reimertz** [comment]
Fixed. Thanks again. <3
